function DREADDgroups = ImportLabels()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/benfulcher/Dropbox (Sydney Uni)/CurrentProjects/Valerio_DREADD/TimeSeries_rightSSctx/DREADD_groups.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/02/02 11:22:00

%% Import the data
[~, ~, raw] = xlsread('DREADD_groups.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,3]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,2);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
DREADDgroups = table;

%% Allocate imported array to column variable names
DREADDgroups.Timeseries_name = stringVectors(:,1);
DREADDgroups.Mouseno = data(:,1);
DREADDgroups.DREADDGroup = categorical(stringVectors(:,2));

end
